=== IndependentIP/compass/src/main/src/org/compass/core/compass-core-mapping.dtd
<!-- Compass Mapping DTD.

<!DOCTYPE compass-core-mapping PUBLIC 
    "-//Compass/Compass Core Mapping DTD 1.0//EN"
    "http://www.opensymphony.com/compass/dtd/compass-core-mapping.dtd">
-->

<!ELEMENT compass-core-mapping (
    (contract|class|resource)* 
)>
    <!ATTLIST compass-core-mapping package CDATA #IMPLIED>

<!ELEMENT resource ( 
    resource-id*,
    (resource-analyzer?),
    (resource-property)*
)>
    <!ATTLIST resource alias CDATA #REQUIRED>
    <!ATTLIST resource sub-index CDATA #IMPLIED>
    <!ATTLIST resource analyzer CDATA #IMPLIED>
    <!ATTLIST resource all (true|false) "true">
    <!ATTLIST resource all-metadata CDATA #IMPLIED>
    <!ATTLIST resource all-term-vector (no|yes|positions|offsets|positions_offsets)  #IMPLIED>
    <!ATTLIST resource all-analyzer CDATA #IMPLIED>

<!ELEMENT resource-id EMPTY
>
    <!ATTLIST resource-id name CDATA #REQUIRED>
    <!ATTLIST resource-id analyzer CDATA #IMPLIED>

<!ELEMENT resource-property EMPTY
>
    <!ATTLIST resource-property name CDATA #REQUIRED>
    <!ATTLIST resource-property store (no|yes|compress) "yes">
    <!ATTLIST resource-property index (no|tokenized|un_tokenized) "tokenized">
    <!ATTLIST resource-property term-vector (no|yes|positions|offsets|positions_offsets) "no">
    <!ATTLIST resource-property reverse (no|reader|string) "no">
    <!ATTLIST resource-property analyzer CDATA #IMPLIED>
    <!ATTLIST resource-property override (true|false) "true">
    <!ATTLIST resource-property exclude-from-all (true|false) #IMPLIED>
    <!ATTLIST resource-property converter CDATA #IMPLIED>
    <!ATTLIST resource-property boost CDATA #IMPLIED>

<!ELEMENT resource-analyzer (
    #PCDATA
)>
    <!ATTLIST resource-analyzer name CDATA #REQUIRED>
    <!ATTLIST resource-analyzer null-analyzer CDATA #IMPLIED>
    <!ATTLIST resource-analyzer converter CDATA #IMPLIED>


<!ELEMENT contract ( 
    id*,
    parent?,
    (analyzer?),
    (property|component|reference|constant)*
)>
    <!ATTLIST contract alias CDATA #REQUIRED>
    <!ATTLIST contract extends CDATA #IMPLIED>
    <!ATTLIST contract analyzer CDATA #IMPLIED>

<!--
    Marks a class as searchable.

    A searchable class is assoiated with an alias, and allows to perform full text search on it's
    mapped properties/fields.
-->
<!ELEMENT class (
    id*,
    parent?,
    (analyzer?),
    (property|component|reference|constant)*
)>
    <!--
        The fully qualified class name (or relative if the package is declared in compass-core-mapping).
    -->
    <!ATTLIST class name CDATA #REQUIRED>
    <!--
        The alias of the Resource that will be mapped to the class.

        The alias can be used to reference the class when performing search operations,
        or for other mappings to extend it.
    -->
    <!ATTLIST class alias CDATA #REQUIRED>
    <!--
        The sub index the searchable class will be saved to. A sub index is a fully functional index.

        When joining several searchable classes into the same index, the search will be much faster,
        but updates perform locks on the sub index level, so it might slow it down.

        Defaults to the class alias value.
    -->
    <!ATTLIST class sub-index CDATA #IMPLIED>
    <!--
        The name of the analyzer that will be used to analyze TOKENIZED properties.

        Defaults to the default analyzer which is one of the internal analyzers that comes with Compass.

        Note, that when using the analyzer mapping (a child mapping of class mapping)
        (for a property value that controls the analyzer), the analyzer attribute will have no effects.
    -->
    <!ATTLIST class analyzer CDATA #IMPLIED>
    <!--
        A comma seperated list of aliases to extend. Can extend a class mapping or a contract mapping.
        Note that can extend more than one class/contract.
    -->
    <!ATTLIST class extends CDATA #IMPLIED>
    <!--
        Specifies if the class is a "root" class or not.

        You should define the searchable class with false if it only acts as mapping
        definitions for a component mapping.
    -->
    <!ATTLIST class root (true|false) "true">
    <!--
        Specifies if the class will be enabled to support polymorphism.

        This is the less prefable way to map an inheritance tree, since the extends attribute
        can be used to statically extend base classes or contracts.

        Defaults to false.
    -->
    <!ATTLIST class poly (true|false) "false">
    <!--
        Specified the class name that will be used to instantiate if poly is set to true.
        If not set, the actual class will be persisted to the index.
    -->
    <!ATTLIST class poly-class CDATA #IMPLIED>
    <!--
        Controls if the searchable class will create it's own internal "all" meta-data.
        The "all" meta-data holds searchable information of all the class searchable content.

        Defaults to true.
    -->
    <!ATTLIST class all (true|false) "true">
    <!--
        The name of the all meta-data.

        Defaults to configuration setting compass.property.all .
    -->
    <!ATTLIST class all-metadata CDATA #IMPLIED>
    <!--
        The term vector value of the all meta-data.

        Defaults to configuration setting compass.property.all.termVector .
    -->
    <!ATTLIST class all-term-vector (no|yes|positions|offsets|positions_offsets)  #IMPLIED>
    <!--
        The name of the analyzer that will be used to analyze the all meta-data.

        Defaults to configuration setting compass.engine.all.analyzer, which in turn,
        defaults to the default analyzer.
    -->
    <!ATTLIST class all-analyzer CDATA #IMPLIED>
    <!--
        The global converter lookup name registered with the configuration. Responsible for converting
        the ClassMapping definition.

        Defaults to compass internal ClassMappingConverter.
    -->
    <!ATTLIST class converter CDATA #IMPLIED>
    <!--
        Specifies the boost level for the class.

        Defaults to 1.0.
    -->
    <!ATTLIST class boost CDATA #IMPLIED>

<!ELEMENT id (
    meta-data*
)>
    <!ATTLIST id name CDATA #REQUIRED>
    <!ATTLIST id class CDATA #IMPLIED>
    <!ATTLIST id analyzer CDATA #IMPLIED>
    <!ATTLIST id accessor CDATA "property">
    <!ATTLIST id managed-id (auto|true|false) "auto">
    <!ATTLIST id exclude-from-all (true|false) "false">
    <!ATTLIST id converter CDATA #IMPLIED>
    <!ATTLIST id boost CDATA #IMPLIED>

<!ELEMENT property (
    meta-data*
)>
    <!ATTLIST property name CDATA #REQUIRED>
    <!ATTLIST property class CDATA #IMPLIED>
    <!ATTLIST property analyzer CDATA #IMPLIED>
    <!ATTLIST property override (true|false) "true">
    <!ATTLIST property accessor CDATA "property">
    <!ATTLIST property managed-id (auto|true|false) "auto">
    <!ATTLIST property managed-id-index (no|un_tokenized) #IMPLIED>
    <!ATTLIST property exclude-from-all (true|false) "false">
    <!ATTLIST property converter CDATA #IMPLIED>
    <!ATTLIST property boost CDATA #IMPLIED>

<!ELEMENT analyzer (
    #PCDATA
)>
    <!ATTLIST analyzer name CDATA #REQUIRED>
    <!ATTLIST analyzer null-analyzer CDATA #IMPLIED>
    <!ATTLIST analyzer accessor (field|property) "property">
    <!ATTLIST analyzer converter CDATA #IMPLIED>

<!ELEMENT component EMPTY
>
    <!ATTLIST component name CDATA #REQUIRED>
    <!ATTLIST component ref-alias CDATA #IMPLIED>
    <!ATTLIST component override (true|false) "true">
    <!ATTLIST component max-depth CDATA #IMPLIED>
    <!ATTLIST component converter CDATA #IMPLIED>
    <!ATTLIST component accessor CDATA "property">

<!ELEMENT reference EMPTY
>
    <!ATTLIST reference name CDATA #REQUIRED>
    <!ATTLIST reference ref-alias CDATA #IMPLIED>
    <!ATTLIST reference ref-comp-alias CDATA #IMPLIED>
    <!ATTLIST reference converter CDATA #IMPLIED>
    <!ATTLIST reference accessor CDATA "property">

<!ELEMENT parent EMPTY
>
    <!ATTLIST parent name CDATA #REQUIRED>
    <!ATTLIST parent converter CDATA #IMPLIED>
    <!ATTLIST parent accessor CDATA "property">

<!ELEMENT constant (
    meta-data,
    meta-data-value+
)>
    <!ATTLIST constant exclude-from-all (true|false) "false">
    <!ATTLIST constant override (true|false) "true">
    <!ATTLIST constant converter CDATA #IMPLIED>

<!ELEMENT meta-data (
    #PCDATA
)>
    <!ATTLIST meta-data store (no|yes|compress) "yes">
    <!ATTLIST meta-data index (no|tokenized|un_tokenized) "tokenized">
    <!ATTLIST meta-data term-vector (no|yes|positions|offsets|positions_offsets) "no">
    <!ATTLIST meta-data reverse (no|reader|string) "no">
    <!ATTLIST meta-data analyzer CDATA #IMPLIED>
    <!ATTLIST meta-data exclude-from-all (true|false) #IMPLIED>
    <!ATTLIST meta-data converter CDATA #IMPLIED>
    <!ATTLIST meta-data format CDATA #IMPLIED>
    <!ATTLIST meta-data boost CDATA #IMPLIED>

<!ELEMENT meta-data-value (
    #PCDATA
)>

=== IndependentIP/compass/src/main/test/org/compass/core/test/transactionisolation/lucene/mapping.cpm.xml
<!DOCTYPE compass-core-mapping PUBLIC 
    "-//Compass/Compass Core Mapping DTD 1.0//EN"
    "http://www.opensymphony.com/compass/dtd/compass-core-mapping.dtd">

<compass-core-mapping package="org.compass.core.test.transactionisolation.lucene">

    <class name="Cyclic1" alias="cyclic1">
    
        <id name="id" />
        
        <property name="value">
            <meta-data>value</meta-data>
        </property>
        
        <reference name="cyclic2" ref-alias="cyclic2" />
        
    </class>

    <class name="Cyclic2" alias="cyclic2">
    
        <id name="id" />
        
        <property name="value">
            <meta-data>value</meta-data>
        </property>
        
        <reference name="cyclic1" ref-alias="cyclic1" />
        
    </class>
</compass-core-mapping>

=== IndependentIP/compass/src/main/test/org/compass/core/test/querybuilder/range1/mapping.cpm.xml
<!DOCTYPE compass-core-mapping PUBLIC
        "-//Compass/Compass Core Mapping DTD 1.0//EN"
        "http://www.opensymphony.com/compass/dtd/compass-core-mapping.dtd">

<compass-core-mapping package="org.compass.core.test.querybuilder.range1">

    <class name="A" alias="a">

        <id name="id" accessor="field"/>

        <property name="value" accessor="field">
            <meta-data format="0,000">value</meta-data>
        </property>

        <property name="date" accessor="field">
            <meta-data>date</meta-data>
        </property>

        <property name="date2" accessor="field">
            <meta-data format="yyyy-MM-dd||dd-MM-yyyy">date2</meta-data>
        </property>

    </class>

</compass-core-mapping>

=== IndependentIP/compass/src/main/test/org/compass/core/test/collection/Collection.cpm.xml
<!DOCTYPE compass-core-mapping PUBLIC 
    "-//Compass/Compass Core Mapping DTD 1.0//EN"
    "http://www.opensymphony.com/compass/dtd/compass-core-mapping.dtd">

<compass-core-mapping package="org.compass.core.test.collection">

    <class name="SimpleTypeCollection" alias="simple-type-col">
    
        <id name="id" />
        
        <property name="value">
            <meta-data>mvalue</meta-data>
        </property>    
    
        <property name="strings" class="java.lang.String">
            <meta-data>mvalue</meta-data>
            <meta-data>svalue</meta-data>
        </property>
        
    </class>

    <class name="ExplicitTypeCollection" alias="explicit-type-col">
    
        <id name="id" />
        
        <property name="value">
            <meta-data>mvalue</meta-data>
        </property>    
    
        <property name="strings" class="java.lang.String">
            <meta-data>mvalue</meta-data>
            <meta-data>svalue</meta-data>
        </property>
        
    </class>

    <class name="A" alias="a">
        
        <id name="id" />
        
        <property name="value">
            <meta-data>value</meta-data>
        </property>    

        <component name="cb" ref-alias="b" />
        
    </class>

    <class name="B" alias="b" root="false">
        
        <property name="value">
            <meta-data>value</meta-data>
        </property>    
        <property name="value2">
            <meta-data>value2</meta-data>
        </property>    
    </class>

    <class name="X" alias="x">
        
        <id name="id" />
        
        <property name="value">
            <meta-data>mvalue</meta-data>
        </property>    

        <reference name="cy" ref-alias="y" />
        
    </class>
    
    <class name="Y" alias="y">
    
        <id name="id" />
        
        <property name="value">
            <meta-data>mvalue</meta-data>
        </property>    
        
    </class>

</compass-core-mapping>

=== IndependentIP/compass/src/main/test/org/compass/core/test/component/twosamecol/mapping.cpm.xml
<!DOCTYPE compass-core-mapping PUBLIC
        "-//Compass/Compass Core Mapping DTD 1.0//EN"
        "http://www.opensymphony.com/compass/dtd/compass-core-mapping.dtd">

<compass-core-mapping package="org.compass.core.test.component.twosamecol">

    <class name="A" alias="a">
        <id name="id" accessor="field" />
        <component name="b1" ref-alias="b" accessor="field" />
        <component name="b2" ref-alias="b" accessor="field" />
    </class>

    <class name="B" alias="b" root="false">
        <property name="value" accessor="field" managed-id-index="un_tokenized">
            <meta-data>value</meta-data>
        </property>
    </class>

</compass-core-mapping>

=== IndependentIP/compass/src/main/test/org/compass/core/test/component/poly1/WithoutPolyComponent.cpm.xml
<?xml version="1.0"?>
<!DOCTYPE compass-core-mapping PUBLIC
        "-//Compass/Compass Core Mapping DTD 1.0//EN"
        "http://www.opensymphony.com/compass/dtd/compass-core-mapping.dtd">

<compass-core-mapping package="org.compass.core.test.component.poly1">

    <class name="WithoutPolyComponent" alias="rootwithoutpolycomponent">
        <id name="id">
            <meta-data>id</meta-data>
        </id>

        <property name="property">
            <meta-data>property</meta-data>
        </property>

        <component name="simpleComponent"/>

    </class>

    <class name="SimpleComponent" alias="scomponent" root="false">
        <property name="componentProperty">
            <meta-data>componentProperty</meta-data>
        </property>
    </class>

</compass-core-mapping>

=== IndependentIP/compass/src/main/test/org/compass/core/test/property/A.cpm.xml
<!DOCTYPE compass-core-mapping PUBLIC 
    "-//Compass/Compass Core Mapping DTD 1.0//EN"
    "http://www.opensymphony.com/compass/dtd/compass-core-mapping.dtd">

<compass-core-mapping package="org.compass.core.test.property">

    <class name="A" alias="a1">
    
        <id name="id" />
        
        <property name="value">
            <meta-data store="yes" index="tokenized">mvalue1</meta-data>
        </property>

    </class>

    <class name="A" alias="a2">
    
        <id name="id" />
        
        <property name="value">
            <meta-data store="no" index="tokenized">mvalue1</meta-data>
        </property>

    </class>

    <class name="A" alias="a3">
    
        <id name="id" />
        
        <property name="value">
            <meta-data store="no" index="tokenized">mvalue1</meta-data>
        </property>

    </class>

    <class name="A" alias="a4">
    
        <id name="id" />
        
        <property name="value">
            <meta-data store="yes" index="un_tokenized">mvalue1</meta-data>
        </property>

    </class>
    
    <class name="A" alias="a5">
    
        <id name="id" />
        
        <property name="value">
            <meta-data store="compress" index="tokenized">mvalue1</meta-data>
        </property>

    </class>

    <class name="A" alias="a6">
    
        <id name="id" />
        
        <property name="value">
            <meta-data store="yes" index="no">mvalue1</meta-data>
        </property>

    </class>

    <class name="A" alias="a7">
    
        <id name="id" />
        
        <property name="value">
            <meta-data store="yes" index="tokenized" term-vector="no">mvalue1</meta-data>
        </property>

    </class>

    <class name="A" alias="a8">
    
        <id name="id" />
        
        <property name="value">
            <meta-data store="yes" index="tokenized" term-vector="yes">mvalue1</meta-data>
        </property>

    </class>

    <class name="A" alias="a9">
    
        <id name="id" />
        
        <property name="value">
            <meta-data store="yes" index="tokenized" term-vector="positions">mvalue1</meta-data>
        </property>

    </class>

    <class name="A" alias="a10">
    
        <id name="id" />
        
        <property name="value">
            <meta-data store="yes" index="tokenized" term-vector="offsets">mvalue1</meta-data>
        </property>

    </class>

    <class name="A" alias="a11">
    
        <id name="id" />
        
        <property name="value">
            <meta-data store="yes" index="tokenized" term-vector="positions_offsets">mvalue1</meta-data>
        </property>

    </class>

    <class name="A" alias="a12">
    
        <id name="id" />
        
        <property name="value">
            <meta-data store="no">mvalue1</meta-data>
        </property>

    </class>

    <class name="A" alias="a13">
    
        <id name="id" />
        
        <property name="value" managed-id="false">
            <meta-data store="no">mvalue1</meta-data>
        </property>

    </class>
</compass-core-mapping>

=== IndependentIP/compass/src/main/test/org/compass/gps/device/jdo/jdo.cpm.xml
<!DOCTYPE compass-core-mapping PUBLIC 
    "-//Compass/Compass Core Mapping DTD 1.0//EN"
    "http://www.opensymphony.com/compass/dtd/compass-core-mapping.dtd">

<compass-core-mapping package="org.compass.gps.device.jdo">

    <contract alias="common">
        <id name="id" />
        <property name="name">
                <meta-data>name</meta-data>
        </property>
        <property name="description">
                <meta-data>description</meta-data>
        </property>
        <property name="price">
                <meta-data>price</meta-data>
        </property>
    </contract>

    <class name="Product" alias="product" extends="common">
    </class>

    <class name="Book" alias="book" extends="common">
        <property name="author">
                <meta-data>author</meta-data>
        </property>
        <property name="isbn">
                <meta-data>isbn</meta-data>
        </property>
        <property name="publisher">
                <meta-data>publisher</meta-data>
        </property>
    </class>

</compass-core-mapping>

=== IndependentIP/compass/src/main/test/org/compass/core/test/nosetter/mapping.cpm.xml
<!DOCTYPE compass-core-mapping PUBLIC 
    "-//Compass/Compass Core Mapping DTD 1.0//EN"
    "http://www.opensymphony.com/compass/dtd/compass-core-mapping.dtd">

<compass-core-mapping package="org.compass.core.test.nosetter">

    <class name="A" alias="a">
    
        <id name="id" accessor="field" />
        
        <property name="value">
            <meta-data>mvalue1</meta-data>
        </property>

        <component name="b" />
    
    </class>

    <class name="B" alias="b" root="false">
    
        <property name="value">
            <meta-data>mvalue2</meta-data>
        </property>
    
    </class>

</compass-core-mapping>
