=== IndependentIP/compass/src/main/src/org/compass/core/compass-core-config.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<xsd:schema xmlns="http://www.opensymphony.com/compass/schema/core-config"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.opensymphony.com/compass/schema/core-config"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified">

    <xsd:element name="compass-core-config">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="compass" type="compassType" minOccurs="1" maxOccurs="1"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="compassType">
        <xsd:sequence>
            <xsd:element name="connection" type="connectionType" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="jndi" type="jndiType" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="mappings" type="mappingsType" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="settings" type="settingsType" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>

    <!-- Connection -->
    <xsd:complexType name="connectionType">
        <xsd:choice>
            <xsd:element name="file" type="fileConnType"/>
            <xsd:element name="mmap" type="mmapConnType"/>
            <xsd:element name="ram" type="ramConnType"/>
            <xsd:element name="jdbc" type="jdbcConnType"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="fileConnType">
        <xsd:attribute name="path" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="mmapConnType">
        <xsd:attribute name="path" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="ramConnType">
        <xsd:attribute name="path" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="jdbcConnType">
        <xsd:sequence>
            <xsd:element name="dataSourceProvider" minOccurs="1" maxOccurs="1">
                <xsd:complexType>
                    <xsd:choice>
                        <xsd:element name="driverManager">
                            <xsd:complexType>
                                <xsd:attribute name="url" type="xsd:string" use="required"/>
                                <xsd:attribute name="username" type="xsd:string" use="required"/>
                                <xsd:attribute name="password" type="xsd:string" use="required"/>
                                <xsd:attribute name="driverClass" type="xsd:string" use="required"/>
                                <xsd:attribute name="autoCommit" type="booleanType" use="optional" default="false"/>
                            </xsd:complexType>
                        </xsd:element>
                        <xsd:element name="c3p0">
                            <xsd:complexType>
                                <xsd:attribute name="url" type="xsd:string" use="required"/>
                                <xsd:attribute name="username" type="xsd:string" use="required"/>
                                <xsd:attribute name="password" type="xsd:string" use="required"/>
                                <xsd:attribute name="driverClass" type="xsd:string" use="required"/>
                                <xsd:attribute name="autoCommit" type="booleanType" use="optional" default="false"/>
                            </xsd:complexType>
                        </xsd:element>
                        <xsd:element name="dbcp">
                            <xsd:complexType>
                                <xsd:attribute name="url" type="xsd:string" use="required"/>
                                <xsd:attribute name="username" type="xsd:string" use="required"/>
                                <xsd:attribute name="password" type="xsd:string" use="required"/>
                                <xsd:attribute name="driverClass" type="xsd:string" use="required"/>
                                <xsd:attribute name="autoCommit" type="booleanType" use="optional" default="false"/>
                                <xsd:attribute name="defaultTransacitonIsolation" type="xsd:nonNegativeInteger"
                                               use="optional" default="0"/>
                                <xsd:attribute name="initialSize" type="xsd:nonNegativeInteger" use="optional"
                                               default="0"/>
                                <xsd:attribute name="maxActive" type="xsd:nonNegativeInteger" use="optional"
                                               default="0"/>
                                <xsd:attribute name="maxIdle" type="xsd:nonNegativeInteger" use="optional" default="0"/>
                                <xsd:attribute name="minIdle" type="xsd:nonNegativeInteger" use="optional" default="0"/>
                                <xsd:attribute name="maxWait" type="xsd:nonNegativeInteger" use="optional" default="0"/>
                                <xsd:attribute name="maxOpenPreparedStatements" type="xsd:nonNegativeInteger"
                                               use="optional" default="0"/>
                                <xsd:attribute name="poolPreparedStatements" type="booleanType" use="optional"
                                               default="false"/>
                            </xsd:complexType>
                        </xsd:element>
                        <xsd:element name="jndi">
                            <xsd:complexType>
                                <xsd:attribute name="lookup" type="xsd:string" use="required"/>
                                <xsd:attribute name="username" type="xsd:string" use="optional"/>
                                <xsd:attribute name="password" type="xsd:string" use="optional"/>
                                <xsd:attribute name="autoCommit" type="booleanType" use="optional" default="false"/>
                            </xsd:complexType>
                        </xsd:element>
                        <xsd:element name="external">
                            <xsd:complexType>
                                <xsd:attribute name="username" type="xsd:string" use="optional"/>
                                <xsd:attribute name="password" type="xsd:string" use="optional"/>
                                <xsd:attribute name="autoCommit" type="booleanType" use="optional" default="false"/>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:choice>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="ddl" minOccurs="0" maxOccurs="1">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="nameColumn" minOccurs="0" maxOccurs="1">
                            <xsd:complexType>
                                <xsd:attribute name="name" type="xsd:string" default="name_"/>
                                <xsd:attribute name="length" type="xsd:positiveInteger"/>
                            </xsd:complexType>
                        </xsd:element>
                        <xsd:element name="valueColumn" minOccurs="0" maxOccurs="1">
                            <xsd:complexType>
                                <xsd:attribute name="name" type="xsd:string" default="value_"/>
                                <xsd:attribute name="length" type="xsd:positiveInteger"/>
                            </xsd:complexType>
                        </xsd:element>
                        <xsd:element name="sizeColumn" minOccurs="0" maxOccurs="1">
                            <xsd:complexType>
                                <xsd:attribute name="name" type="xsd:string" default="size_"/>
                            </xsd:complexType>
                        </xsd:element>
                        <xsd:element name="lastModifiedColumn" minOccurs="0" maxOccurs="1">
                            <xsd:complexType>
                                <xsd:attribute name="name" type="xsd:string" default="lf_"/>
                            </xsd:complexType>
                        </xsd:element>
                        <xsd:element name="deletedColumn" minOccurs="0" maxOccurs="1">
                            <xsd:complexType>
                                <xsd:attribute name="name" type="xsd:string" default="deleted_"/>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="fileEntries" minOccurs="0" maxOccurs="1">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="fileEntry" minOccurs="1" maxOccurs="unbounded">
                            <xsd:complexType>
                                <xsd:sequence>
                                    <xsd:element name="indexInput" minOccurs="0" maxOccurs="1">
                                        <xsd:complexType>
                                            <xsd:attribute name="type" use="optional">
                                                <xsd:simpleType>
                                                    <xsd:restriction base="xsd:string">
                                                        <xsd:enumeration value="org.apache.lucene.store.jdbc.index.FetchOnBufferReadJdbcIndexInput"/>
                                                        <xsd:enumeration value="org.apache.lucene.store.jdbc.index.FetchOnOpenJdbcIndexInput"/>
                                                        <xsd:enumeration value="org.apache.lucene.store.jdbc.index.FetchPerTransactionJdbcIndexInput"/>
                                                    </xsd:restriction>
                                                </xsd:simpleType>
                                            </xsd:attribute>
                                            <xsd:attribute name="typeClass" type="xsd:string" use="optional" />
                                            <xsd:attribute name="bufferSize" type="xsd:positiveInteger" use="optional" />
                                        </xsd:complexType>
                                    </xsd:element>
                                    <xsd:element name="indexOutput" minOccurs="0" maxOccurs="1">
                                        <xsd:complexType>
                                            <xsd:attribute name="type" use="optional">
                                                <xsd:simpleType>
                                                    <xsd:restriction base="xsd:string">
                                                        <xsd:enumeration value="org.apache.lucene.store.jdbc.index.RAMAndFileJdbcIndexOutput"/>
                                                        <xsd:enumeration value="org.apache.lucene.store.jdbc.index.RAMJdbcIndexOutput"/>
                                                    </xsd:restriction>
                                                </xsd:simpleType>
                                            </xsd:attribute>
                                            <xsd:attribute name="typeClass" type="xsd:string" use="optional" />
                                            <xsd:attribute name="bufferSize" type="xsd:positiveInteger" use="optional" />
                                            <xsd:attribute name="threshold" type="xsd:positiveInteger" use="optional" />
                                        </xsd:complexType>
                                    </xsd:element>
                                    <xsd:element name="setting" type="settingType" minOccurs="0" maxOccurs="unbounded"/>
                                </xsd:sequence>
                                <xsd:attribute name="name" type="xsd:string" use="required"/>
                                <xsd:attribute name="type" use="optional">
                                    <xsd:simpleType>
                                        <xsd:restriction base="xsd:string">
                                            <xsd:enumeration value="org.apache.lucene.store.jdbc.handler.NoOpFileEntryHandler"/>
                                            <xsd:enumeration value="org.apache.lucene.store.jdbc.handler.MarkDeleteFileEntryHandler"/>
                                            <xsd:enumeration value="org.apache.lucene.store.jdbc.handler.ActualDeleteFileEntryHandler"/>
                                        </xsd:restriction>
                                    </xsd:simpleType>
                                </xsd:attribute>
                                <xsd:attribute name="typeClass" type="xsd:string" use="optional" />
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="managed" type="booleanType" use="optional" default="false"/>
        <xsd:attribute name="dialectClass" type="xsd:string" use="optional"/>
        <xsd:attribute name="dialect" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="org.apache.lucene.store.jdbc.dialect.DB2Dialect"/>
                    <xsd:enumeration value="org.apache.lucene.store.jdbc.dialect.DerbyDialect"/>
                    <xsd:enumeration value="org.apache.lucene.store.jdbc.dialect.FirebirdDialect"/>
                    <xsd:enumeration value="org.apache.lucene.store.jdbc.dialect.HSQLDialect"/>
                    <xsd:enumeration value="org.apache.lucene.store.jdbc.dialect.InterbaseDialect"/>
                    <xsd:enumeration value="org.apache.lucene.store.jdbc.dialect.MySQLDialect"/>
                    <xsd:enumeration value="org.apache.lucene.store.jdbc.dialect.MySQLInnoDBDialect"/>
                    <xsd:enumeration value="org.apache.lucene.store.jdbc.dialect.MySQLMyISAMDialect"/>
                    <xsd:enumeration value="org.apache.lucene.store.jdbc.dialect.Oracle8Dialect"/>
                    <xsd:enumeration value="org.apache.lucene.store.jdbc.dialect.OracleDialect"/>
                    <xsd:enumeration value="org.apache.lucene.store.jdbc.dialect.PostgresDialect"/>
                    <xsd:enumeration value="org.apache.lucene.store.jdbc.dialect.SQLServerDialect"/>
                    <xsd:enumeration value="org.apache.lucene.store.jdbc.dialect.SybaseDialect"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="useCommitLocks" type="booleanType" use="optional" default="false"/>
        <xsd:attribute name="deleteMarkDeletedDelta" type="xsd:positiveInteger" use="optional"/>
        <xsd:attribute name="lockClass" type="xsd:string" use="optional"/>
        <xsd:attribute name="lock" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="org.apache.lucene.store.jdbc.lock.SelectForUpdateLock"/>
                    <xsd:enumeration value="org.apache.lucene.store.jdbc.lock.PhantomReadLock"/>
                    <xsd:enumeration value="org.apache.lucene.store.jdbc.lock.NoOpLock"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <!-- JNDI -->
    <xsd:complexType name="jndiType">
        <xsd:sequence>
            <xsd:element name="environment" minOccurs="0" maxOccurs="1">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="property" minOccurs="1" maxOccurs="unbounded">
                            <xsd:complexType>
                                <xsd:attribute name="name" type="xsd:string" use="required"/>
                                <xsd:attribute name="value" type="xsd:string" use="required"/>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="register" type="booleanType" default="false"/>
        <xsd:attribute name="class" type="xsd:string" use="optional"/>
        <xsd:attribute name="url" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <!-- Mapping Types -->
    <xsd:complexType name="mappingsType">
        <xsd:choice>
            <xsd:element name="resource">
                <xsd:complexType>
                    <xsd:attribute name="location" type="xsd:string" use="required"/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="jar">
                <xsd:complexType>
                    <xsd:attribute name="path" type="xsd:string" use="required"/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="file">
                <xsd:complexType>
                    <xsd:attribute name="path" type="xsd:string" use="required"/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="dir">
                <xsd:complexType>
                    <xsd:attribute name="path" type="xsd:string" use="required"/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="package">
                <xsd:complexType>
                    <xsd:attribute name="name" type="xsd:string" use="required"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:choice>
    </xsd:complexType>

    <!-- Settings Types -->
    <xsd:complexType name="settingsType">
        <xsd:sequence>
            <xsd:element name="setting" type="settingType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="settingType">
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="value" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="booleanType">
        <xsd:restriction base="xsd:NMTOKEN">
            <xsd:enumeration value="true"/>
            <xsd:enumeration value="false"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== IndependentIP/compass/src/main/test/org/compass/gps/device/hibernate/transaction/compass.cfg.xml
<compass-core-config xmlns="http://www.opensymphony.com/compass/schema/core-config"
	   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xsi:schemaLocation="http://www.opensymphony.com/compass/schema/core-config http://www.opensymphony.com/compass/schema/compass-core-config.xsd">

    <compass name="default">

        <connection>
            <file path="target/testindex" />
        </connection>

        <transaction factory="org.compass.gps.device.hibernate.HibernateSyncTransactionFactory" />

        <mappings>
            <class name="org.compass.gps.device.hibernate.transaction.A" />
        </mappings>

        <settings>
            <setting name="compass.engine.optimizer.type" value="org.compass.core.lucene.engine.optimizer.NullOptimizer" />
        </settings>
    </compass>

</compass-core-config>

=== IndependentIP/compass/src/main/test/org/compass/core/test/schema/jdbc-ddl.cfg.xml
<compass-core-config xmlns="http://www.opensymphony.com/compass/schema/core-config"
	   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xsi:schemaLocation="http://www.opensymphony.com/compass/schema/core-config http://www.opensymphony.com/compass/schema/compass-core-config.xsd">

    <compass name="default">

        <connection>
            <jdbc dialect="org.apache.lucene.store.jdbc.dialect.HSQLDialect" managed="false">
                <dataSourceProvider>
                    <jndi lookup="testds" username="testusername" password="testpassword" />
                </dataSourceProvider>
                <ddl>
                    <nameColumn name="myname" length="70" />
                    <sizeColumn name="mysize" />
                </ddl>
            </jdbc>
        </connection>
    </compass>

</compass-core-config>
